
> ping-service@0.1.0 synth
> cdk synth

Resources:
  TaskDefinitionTaskRoleFD40A61D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PingServiceStack/TaskDefinition/TaskRole/Resource
  TaskDefinitionB36D86D9:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image:
            Fn::Sub: 903312262684.dkr.ecr.eu-west-1.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-903312262684-eu-west-1:119e3ab26fb44b2e0d88ab314a1d90911a889e8f5441f7272f02b9e7f9cb6a85
          LinuxParameters:
            Capabilities: {}
            InitProcessEnabled: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: TaskDefinitionappLogGroup1EDFCB10
              awslogs-stream-prefix: ecs
              awslogs-region: eu-west-1
          Name: app
          PortMappings:
            - AppProtocol: http
              ContainerPort: 3000
              Name: app
              Protocol: tcp
      Cpu: "256"
      ExecutionRoleArn:
        Fn::GetAtt:
          - TaskDefinitionExecutionRole8D61C2FB
          - Arn
      Family: PingServiceStackTaskDefinitionDDE9E71E
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
      TaskRoleArn:
        Fn::GetAtt:
          - TaskDefinitionTaskRoleFD40A61D
          - Arn
    Metadata:
      aws:cdk:path: PingServiceStack/TaskDefinition/Resource
  TaskDefinitionappLogGroup1EDFCB10:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: PingServiceStack/TaskDefinition/app/LogGroup/Resource
  TaskDefinitionExecutionRole8D61C2FB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PingServiceStack/TaskDefinition/ExecutionRole/Resource
  TaskDefinitionExecutionRoleDefaultPolicy1F3406F5:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
            Effect: Allow
            Resource: arn:aws:ecr:eu-west-1:903312262684:repository/cdk-hnb659fds-container-assets-903312262684-eu-west-1
          - Action: ecr:GetAuthorizationToken
            Effect: Allow
            Resource: "*"
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - TaskDefinitionappLogGroup1EDFCB10
                - Arn
        Version: "2012-10-17"
      PolicyName: TaskDefinitionExecutionRoleDefaultPolicy1F3406F5
      Roles:
        - Ref: TaskDefinitionExecutionRole8D61C2FB
    Metadata:
      aws:cdk:path: PingServiceStack/TaskDefinition/ExecutionRole/DefaultPolicy/Resource
  ServiceD69D759B:
    Type: AWS::ECS::Service
    Properties:
      Cluster: PingPongVpcStack-ClusterEB0386A7-W2QrlRtdRpPC
      DeploymentConfiguration:
        Alarms:
          AlarmNames: []
          Enable: false
          Rollback: false
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      EnableECSManagedTags: false
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::GetAtt:
                - ServiceSecurityGroupC96ED6A7
                - GroupId
          Subnets:
            - subnet-0f1e53008bb8989e9
            - subnet-0b7fdee0338b03430
            - subnet-0f76d11d0420aee26
      ServiceRegistries:
        - RegistryArn:
            Fn::GetAtt:
              - ServiceCloudmapService046058A4
              - Arn
      TaskDefinition:
        Ref: TaskDefinitionB36D86D9
    DependsOn:
      - TaskDefinitionTaskRoleFD40A61D
    Metadata:
      aws:cdk:path: PingServiceStack/Service/Service
  ServiceCloudmapService046058A4:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      DnsConfig:
        DnsRecords:
          - TTL: 60
            Type: A
        NamespaceId: ns-w44g2x4tntiv45zb
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      NamespaceId: ns-w44g2x4tntiv45zb
    DependsOn:
      - TaskDefinitionTaskRoleFD40A61D
    Metadata:
      aws:cdk:path: PingServiceStack/Service/CloudmapService/Resource
  ServiceSecurityGroupC96ED6A7:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PingServiceStack/Service/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-02864a1ed83e223e7
    DependsOn:
      - TaskDefinitionTaskRoleFD40A61D
    Metadata:
      aws:cdk:path: PingServiceStack/Service/SecurityGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/22QQU/DMAyFfwv3NLAdYFdgAiHtMHXcp5B6kdc2nuy0UFX57yRtQYA4+eV7ip/ttd7c6Zsr8y6FreqiwTc9HoKxtUroOIIVPT4ZdibAq5F6Cyf0GJC8ejz5v4R8MOiBf7Ad+u5jb9i0EIBFLb0OwD1ayE0WGRWaVo8lNROd6p4atEN+ziqqhlwaaEfumam7ZOdLRwWWj0YEgugt2Rr4pTUO7jPJni7hQoKBeHgwAkrm3ArFUg88pL3/GQrsOhu2YwzDd+gvEKMqQajj9HVKS/dz6N20xmJE5akCfZbrfrXRq9t08rMgFtz5gC3ocq6f0NrUo44BAAA=
    Metadata:
      aws:cdk:path: PingServiceStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

